name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - markovify
  - pandas
  - matplotlib
  - scipy
  - scikit-learn 